

ALTER TABLE [dbo].[BatchInvoices] DROP CONSTRAINT [FK_BatchInvoices_Invoice_Header_Enrich_InvoiceId]
go
ALTER TABLE [dbo].[Invoice_Attachments] DROP CONSTRAINT [FK_Invoice_Attachments_Invoice_Header_Enrich_InvoiceId]
go
ALTER TABLE [dbo].[Tab_Invoices] DROP CONSTRAINT [FK_Tab_Invoices_Invoice_Header_Enrich_InvoiceId]
go

CREATE TABLE [dbo].[Invoice_Header_Enrich_4C0D9E41399D4CCC8D67B25DD3DC6240]
(
 [ID] Int NOT NULL,
 [PROCESSED_DT] Datetime2(7) NULL,
 [SQL_filename] Varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [RETURN_FILE] Nvarchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [TRANSACTION_FROM] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [TRANSACTION_TO] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [TRANSACTION_TYPE] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [VERSION] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [PO_NUMBER] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [PO_RELEASE_NUMBER] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [USERNAME] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [NOTE] Varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [DATE_INVOICED] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [DATE_ORDERED] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [DATE_REQUIRED] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [DATE_SHIPPED] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [PRICE_SOURCE] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SUPPLIER] Varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [REMIT_TO_NAME] Varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [REMIT_TO_STREET1] Varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [REMIT_TO_STREET2] Varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [REMIT_TO_CITY] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [REMIT_TO_STATE] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [REMIT_TO_ZIP] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [BILL_TO_NUMBER] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [BILL_TO_NAME] Varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [BILL_TO_STREET1] Varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [BILL_TO_STREET2] Varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [BILL_TO_CITY] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [BILL_TO_STATE] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [BILL_TO_ZIP] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SHIP_TO_NUMBER] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SHIP_TO_NAME] Varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SHIP_TO_STREET1] Varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SHIP_TO_STREET2] Varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SHIP_TO_CITY] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SHIP_TO_STATE] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SHIP_TO_ZIP] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SHIP_VIA] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [CARRIER_NAME] Varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [FOB] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SUPPLIER_REGION_NUMBER] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SUPPLIER_WAREHOUSE_NUMBER] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SUPPLIER_ORDER_NUMBER] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SUPPLIER_INVOICE_NUMBER] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [JOB_NUMBER] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [JOB_NAME] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [TOTAL_MATERIAL_AMT] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [AMT_SUBJECT_TO_DISCOUNT] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [FREIGHT_AMT] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [TAX_DESCR] Varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [TAX_AMT] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [TAX_PERCENT] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [TAX_LIBABILITY_AMT] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [OTHER_CHARGE_AMT] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [OTHER_CHARGE_DESC] Varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [TOTAL_INVOICE_AMT] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [TERMS_NET_DAYS] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [CREDIT_MEMO] Varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [TOTAL_DISCOUNT_AMT] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [DISCOUNT_PERCENT] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [DISCOUNT_DATE] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [DISCOUNT_DAYS] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [TOTAL_LESS_DISCOUNT] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [INVOICE_TERMS] Varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [TERMS_TYPE] Varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [PAYMENT_DUE_DATE] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [TAX_ID] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [CURRENCY_TYPE] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [CONTACT_NAME] Varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [CONTACT_PHONE] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [CONTACT_FAX] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [CONTACT_EMAIL] Varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SPARE_ONE] Varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SPARE_TWO] Varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SPARE_THREE] Varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SPARE_FOUR] Varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [EDI_ISA_CONTROL_NO] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [EDI_GS_CONTROL_NO] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [EDI_ST_CONTROL_NO] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [INITIAL_PROCESS_DATE] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [INITIAL_PROCESS_TIME] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [EMAILADDRESS] Varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [INVOICE_FLAG] Varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [INBOUNDFILENAME] Varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [RULES] Varchar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [RECEIVED_DT] Datetime2(7) NULL,
 [UpdatedOn] Datetime2(7) NOT NULL,
 [Status] Nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 [InvoiceHeaderId] Int NULL,
 [BatchId] Nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [AssignedToId] Int NULL,
 [IsDeleted] Bit DEFAULT ((0)) NULL,
 [TagId] Int NULL,
 [UpdatedBy] Nvarchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [RoutingCode] Nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [OrderDate] Date NULL,
 [CostCenter] Nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [WorkOrderNumber] Nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [PoType] Nvarchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [SubJobNumber] Nvarchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [Change] Nvarchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [PAYMENT_TERMS] Nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [DISTRIBUTOR_QUOTE_NUMBER] Nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [PaymentType] Nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [CheckNumber] Nvarchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [CashGLAccount] Nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [CheckDate] Date NULL,
 [CardNumber] Nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [ACCOUNTING_DATE] Date NULL,
 [GROSS_AMOUNT] Decimal(18,6) NULL,
 [NET_AMOUNT] Decimal(18,6) NULL,
 [INVOICE_TYPE] Nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [GL_DATE] Date NULL,
 [SUPPLIER_NUMBER] Nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [VENDOR_NUMBER] Nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [VENDOR_NAME] Nvarchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [HeaderStatus] Nvarchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT ('O') NOT NULL,
 [BankAccountCCCode] Nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [DefaultSupplier] Nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [ACTUAL_GROSS_AMOUNT] Decimal(18,6) DEFAULT ((0.00)) NOT NULL,
 [ACTUAL_NET_AMOUNT] Decimal(18,6) DEFAULT ((0.00)) NOT NULL,
 [ACTUAL_FREIGHT_AMT] Decimal(18,6) DEFAULT ((0.00)) NOT NULL,
 [ACTUAL_OTHER_CHARGE_AMT] Decimal(18,6) DEFAULT ((0.00)) NOT NULL,
 [ACTUAL_TAX_AMT] Decimal(18,6) DEFAULT ((0.00)) NOT NULL,
 [ACTUAL_DISCOUNT_AMT] Decimal(18,6) DEFAULT ((0.00)) NOT NULL,
 [PO_EXIST] Bit DEFAULT ((0)) NOT NULL,
 [INVOICE_EXIST] Bit DEFAULT ((0)) NOT NULL,
 [TaxAppliedAsLine] Bit DEFAULT ((0)) NOT NULL,
 [FreightAppliedAsLine] Bit DEFAULT ((0)) NOT NULL,
 [OtherAppliedAsLine] Bit DEFAULT ((0)) NOT NULL,
 [ExchangeQtyAndPrice] Bit DEFAULT ((0)) NOT NULL,
 [AppliedAsLumpSum] Bit DEFAULT ((0)) NOT NULL,
 [ClosePOOnExport] Bit DEFAULT ((0)) NOT NULL,
 [ClosePOOnNoQuantityRemaining] Bit DEFAULT ((0)) NOT NULL,
 [ForceErrorCorrection] Bit DEFAULT ((0)) NOT NULL,
 [ExportLinesWithoutValidation] Bit DEFAULT ((0)) NOT NULL,
 [IsProcessed] Bit DEFAULT ((0)) NOT NULL,
 [HasSupplierMatched] Bit DEFAULT ((0)) NOT NULL,
 [AUTO_VALIDATED] Bit DEFAULT ((0)) NOT NULL,
 [BRANCH_ID] Nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [ERP_NOTES] Varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [REMARKS] Varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [DUPLICATE_PO] Bit DEFAULT ((0)) NOT NULL,
 [INVOICE_ENTRY_DT] Datetime2(7) DEFAULT (getdate()) NULL,
 [INVOICE_VALIDATED_BY] Varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [INVOICE_VALIDATION_PROCESSED_DT] Datetime2(7) NULL,
 [INVOICE_AUTO_VALIDATION_DT] Datetime2(7) NULL,
 [INVOICE_VALIDATION_UPDATED_DT] Datetime2(7) NULL,
 [INVOICE_VALIDATION_DATA_SET] Nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
ON [Header_Enrich_Data]
TEXTIMAGE_ON [PRIMARY]
go
INSERT INTO [dbo].[Invoice_Header_Enrich_4C0D9E41399D4CCC8D67B25DD3DC6240] ([ID], [PROCESSED_DT], [SQL_filename], [RETURN_FILE], [TRANSACTION_FROM], [TRANSACTION_TO], [TRANSACTION_TYPE], [VERSION], [PO_NUMBER], [PO_RELEASE_NUMBER], [USERNAME], [NOTE], [DATE_INVOICED], [DATE_ORDERED], [DATE_REQUIRED], [DATE_SHIPPED], [PRICE_SOURCE], [SUPPLIER], [REMIT_TO_NAME], [REMIT_TO_STREET1], [REMIT_TO_STREET2], [REMIT_TO_CITY], [REMIT_TO_STATE], [REMIT_TO_ZIP], [BILL_TO_NUMBER], [BILL_TO_NAME], [BILL_TO_STREET1], [BILL_TO_STREET2], [BILL_TO_CITY], [BILL_TO_STATE], [BILL_TO_ZIP], [SHIP_TO_NUMBER], [SHIP_TO_NAME], [SHIP_TO_STREET1], [SHIP_TO_STREET2], [SHIP_TO_CITY], [SHIP_TO_STATE], [SHIP_TO_ZIP], [SHIP_VIA], [CARRIER_NAME], [FOB], [SUPPLIER_REGION_NUMBER], [SUPPLIER_WAREHOUSE_NUMBER], [SUPPLIER_ORDER_NUMBER], [SUPPLIER_INVOICE_NUMBER], [JOB_NUMBER], [JOB_NAME], [TOTAL_MATERIAL_AMT], [AMT_SUBJECT_TO_DISCOUNT], [FREIGHT_AMT], [TAX_DESCR], [TAX_AMT], [TAX_PERCENT], [TAX_LIBABILITY_AMT], [OTHER_CHARGE_AMT], [OTHER_CHARGE_DESC], [TOTAL_INVOICE_AMT], [TERMS_NET_DAYS], [CREDIT_MEMO], [TOTAL_DISCOUNT_AMT], [DISCOUNT_PERCENT], [DISCOUNT_DATE], [DISCOUNT_DAYS], [TOTAL_LESS_DISCOUNT], [INVOICE_TERMS], [TERMS_TYPE], [PAYMENT_DUE_DATE], [TAX_ID], [CURRENCY_TYPE], [CONTACT_NAME], [CONTACT_PHONE], [CONTACT_FAX], [CONTACT_EMAIL], [SPARE_ONE], [SPARE_TWO], [SPARE_THREE], [SPARE_FOUR], [EDI_ISA_CONTROL_NO], [EDI_GS_CONTROL_NO], [EDI_ST_CONTROL_NO], [INITIAL_PROCESS_DATE], [INITIAL_PROCESS_TIME], [EMAILADDRESS], [INVOICE_FLAG], [INBOUNDFILENAME], [RULES], [RECEIVED_DT], [UpdatedOn], [Status], [InvoiceHeaderId], [BatchId], [AssignedToId], [IsDeleted], [TagId], [UpdatedBy], [RoutingCode], [OrderDate], [CostCenter], [WorkOrderNumber], [PoType], [SubJobNumber], [Change], [PAYMENT_TERMS], [DISTRIBUTOR_QUOTE_NUMBER], [PaymentType], [CheckNumber], [CashGLAccount], [CheckDate], [CardNumber], [ACCOUNTING_DATE], [GROSS_AMOUNT], [NET_AMOUNT], [INVOICE_TYPE], [GL_DATE], [SUPPLIER_NUMBER], [VENDOR_NUMBER], [VENDOR_NAME], [HeaderStatus], [BankAccountCCCode], [DefaultSupplier], [ACTUAL_GROSS_AMOUNT], [ACTUAL_NET_AMOUNT], [ACTUAL_FREIGHT_AMT], [ACTUAL_OTHER_CHARGE_AMT], [ACTUAL_TAX_AMT], [ACTUAL_DISCOUNT_AMT], [PO_EXIST], [INVOICE_EXIST], [TaxAppliedAsLine], [FreightAppliedAsLine], [OtherAppliedAsLine], [ExchangeQtyAndPrice], [AppliedAsLumpSum], [ClosePOOnExport], [ClosePOOnNoQuantityRemaining], [ForceErrorCorrection], [ExportLinesWithoutValidation], [IsProcessed], [HasSupplierMatched], [AUTO_VALIDATED], [BRANCH_ID], [ERP_NOTES], [REMARKS], [DUPLICATE_PO], [INVOICE_ENTRY_DT], [INVOICE_VALIDATED_BY], [INVOICE_VALIDATION_PROCESSED_DT], [INVOICE_AUTO_VALIDATION_DT], [INVOICE_VALIDATION_UPDATED_DT], [INVOICE_VALIDATION_DATA_SET]) SELECT [ID], [PROCESSED_DT], [SQL_filename], [RETURN_FILE], [TRANSACTION_FROM], [TRANSACTION_TO], [TRANSACTION_TYPE], [VERSION], [PO_NUMBER], [PO_RELEASE_NUMBER], [USERNAME], [NOTE], [DATE_INVOICED], [DATE_ORDERED], [DATE_REQUIRED], [DATE_SHIPPED], [PRICE_SOURCE], [SUPPLIER], [REMIT_TO_NAME], [REMIT_TO_STREET1], [REMIT_TO_STREET2], [REMIT_TO_CITY], [REMIT_TO_STATE], [REMIT_TO_ZIP], [BILL_TO_NUMBER], [BILL_TO_NAME], [BILL_TO_STREET1], [BILL_TO_STREET2], [BILL_TO_CITY], [BILL_TO_STATE], [BILL_TO_ZIP], [SHIP_TO_NUMBER], [SHIP_TO_NAME], [SHIP_TO_STREET1], [SHIP_TO_STREET2], [SHIP_TO_CITY], [SHIP_TO_STATE], [SHIP_TO_ZIP], [SHIP_VIA], [CARRIER_NAME], [FOB], [SUPPLIER_REGION_NUMBER], [SUPPLIER_WAREHOUSE_NUMBER], [SUPPLIER_ORDER_NUMBER], [SUPPLIER_INVOICE_NUMBER], [JOB_NUMBER], [JOB_NAME], [TOTAL_MATERIAL_AMT], [AMT_SUBJECT_TO_DISCOUNT], [FREIGHT_AMT], [TAX_DESCR], [TAX_AMT], [TAX_PERCENT], [TAX_LIBABILITY_AMT], [OTHER_CHARGE_AMT], [OTHER_CHARGE_DESC], [TOTAL_INVOICE_AMT], [TERMS_NET_DAYS], [CREDIT_MEMO], [TOTAL_DISCOUNT_AMT], [DISCOUNT_PERCENT], [DISCOUNT_DATE], [DISCOUNT_DAYS], [TOTAL_LESS_DISCOUNT], [INVOICE_TERMS], [TERMS_TYPE], [PAYMENT_DUE_DATE], [TAX_ID], [CURRENCY_TYPE], [CONTACT_NAME], [CONTACT_PHONE], [CONTACT_FAX], [CONTACT_EMAIL], [SPARE_ONE], [SPARE_TWO], [SPARE_THREE], [SPARE_FOUR], [EDI_ISA_CONTROL_NO], [EDI_GS_CONTROL_NO], [EDI_ST_CONTROL_NO], [INITIAL_PROCESS_DATE], [INITIAL_PROCESS_TIME], [EMAILADDRESS], [INVOICE_FLAG], [INBOUNDFILENAME], [RULES], [RECEIVED_DT], [UpdatedOn], [Status], [InvoiceHeaderId], [BatchId], [AssignedToId], [IsDeleted], [TagId], [UpdatedBy], [RoutingCode], [OrderDate], [CostCenter], [WorkOrderNumber], [PoType], [SubJobNumber], [Change], [PAYMENT_TERMS], [DISTRIBUTOR_QUOTE_NUMBER], [PaymentType], [CheckNumber], [CashGLAccount], [CheckDate], [CardNumber], [ACCOUNTING_DATE], [GROSS_AMOUNT], [NET_AMOUNT], [INVOICE_TYPE], [GL_DATE], [SUPPLIER_NUMBER], [VENDOR_NUMBER], [VENDOR_NAME], [HeaderStatus], [BankAccountCCCode], [DefaultSupplier], [ACTUAL_GROSS_AMOUNT], [ACTUAL_NET_AMOUNT], [ACTUAL_FREIGHT_AMT], [ACTUAL_OTHER_CHARGE_AMT], [ACTUAL_TAX_AMT], [ACTUAL_DISCOUNT_AMT], [PO_EXIST], [INVOICE_EXIST], [TaxAppliedAsLine], [FreightAppliedAsLine], [OtherAppliedAsLine], [ExchangeQtyAndPrice], [AppliedAsLumpSum], [ClosePOOnExport], [ClosePOOnNoQuantityRemaining], [ForceErrorCorrection], [ExportLinesWithoutValidation], [IsProcessed], [HasSupplierMatched], [AUTO_VALIDATED], [BRANCH_ID], [ERP_NOTES], [REMARKS], [DUPLICATE_PO], [INVOICE_ENTRY_DT], [INVOICE_VALIDATED_BY], [INVOICE_VALIDATION_PROCESSED_DT], [INVOICE_AUTO_VALIDATION_DT], [INVOICE_VALIDATION_UPDATED_DT], [INVOICE_VALIDATION_DATA_SET] FROM [dbo].[Invoice_Header_Enrich]
go



DROP TABLE [dbo].[Invoice_Header_Enrich]
go
EXEC sp_rename '[dbo].[Invoice_Header_Enrich_4C0D9E41399D4CCC8D67B25DD3DC6240]', 'Invoice_Header_Enrich', 'OBJECT'
go


ALTER TABLE [dbo].[Invoice_Header_Enrich] ADD CONSTRAINT [DF_Invoice_Header_Enrich_UpdatedOn] DEFAULT (getdate()) FOR [UpdatedOn]
go
ALTER TABLE [dbo].[Invoice_Header_Enrich] ADD CONSTRAINT [DF_Invoice_Header_Enrich_Status] DEFAULT ('New') FOR [Status]
go

ALTER TABLE [dbo].[Invoice_Header_Enrich] ADD CONSTRAINT [PK_Invoice_Header_Enrich] PRIMARY KEY ([ID])
 ON [Header_Enrich_Data]
go

GRANT INSERT ON [dbo].[Invoice_Header_Enrich] TO [mindfire] AS [dbo]
go
GRANT SELECT ON [dbo].[Invoice_Header_Enrich] TO [mindfire] AS [dbo]
go
ALTER TABLE [dbo].[BatchInvoices] ADD CONSTRAINT [FK_BatchInvoices_Invoice_Header_Enrich_InvoiceId] FOREIGN KEY ([InvoiceId]) REFERENCES [dbo].[Invoice_Header_Enrich] ([ID]) ON UPDATE NO ACTION ON DELETE CASCADE
go


ALTER TABLE [dbo].[Invoice_Attachments] ADD CONSTRAINT [FK_Invoice_Attachments_Invoice_Header_Enrich_InvoiceId] FOREIGN KEY ([InvoiceId]) REFERENCES [dbo].[Invoice_Header_Enrich] ([ID]) ON UPDATE NO ACTION ON DELETE CASCADE
go


ALTER TABLE [dbo].[Tab_Invoices] ADD CONSTRAINT [FK_Tab_Invoices_Invoice_Header_Enrich_InvoiceId] FOREIGN KEY ([InvoiceId]) REFERENCES [dbo].[Invoice_Header_Enrich] ([ID]) ON UPDATE NO ACTION ON DELETE CASCADE
go


CREATE INDEX [IX_InvoiceHeaderEnrich_TRANSACTION_TO] ON [dbo].[Invoice_Header_Enrich] ([TRANSACTION_TO])
 ON [Header_Enrich_Index]
go

CREATE INDEX [IX_InvoiceHeaderEnrich_TRANSACTION_FROM] ON [dbo].[Invoice_Header_Enrich] ([TRANSACTION_FROM])
 ON [Header_Enrich_Index]
go

CREATE INDEX [IX_InvoiceHeaderEnrich_EmailAddress] ON [dbo].[Invoice_Header_Enrich] ([EMAILADDRESS])
 ON [Header_Enrich_Index]
go

CREATE INDEX [IX_InvoiceHeaderEnrich_Status] ON [dbo].[Invoice_Header_Enrich] ([Status])
 ON [Header_Enrich_Index]
go
