


CREATE TABLE [dbo].[INVOICELOG_AF6304FD875644D98D97D1CA017E6F4A]
(
 [LOGID] Bigint NOT NULL,
 [INVOICENO] Nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 [PONO] Nvarchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 [PROCESSDATE] Date DEFAULT (NULL) NULL,
 [PROCESSTIME] Datetime2(7) DEFAULT (NULL) NULL,
 [IMAGESENT] Int DEFAULT (NULL) NULL,
 [IMAGESENDDATE] Date DEFAULT (NULL) NULL,
 [IMAGESENDTIME] Datetime2(7) DEFAULT (NULL) NULL,
 [FILENAME] Nvarchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 [DISTRIBUTORID] Nvarchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 [CONTRACTORID] Nvarchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT ('0') NOT NULL
)
ON [Invoice_Log_Data]
go
INSERT INTO [dbo].[INVOICELOG_AF6304FD875644D98D97D1CA017E6F4A] ([LOGID], [INVOICENO], [PONO], [PROCESSDATE], [PROCESSTIME], [IMAGESENT], [IMAGESENDDATE], [IMAGESENDTIME], [FILENAME], [DISTRIBUTORID], [CONTRACTORID]) SELECT [LOGID], [INVOICENO], [PONO], [PROCESSDATE], [PROCESSTIME], [IMAGESENT], [IMAGESENDDATE], [IMAGESENDTIME], [FILENAME], [DISTRIBUTORID], [CONTRACTORID] FROM [dbo].[INVOICELOG]
go



DROP TABLE [dbo].[INVOICELOG]
go
EXEC sp_rename '[dbo].[INVOICELOG_AF6304FD875644D98D97D1CA017E6F4A]', 'INVOICELOG', 'OBJECT'
go


CREATE INDEX [ix_invoicelog_invoiceno] ON [dbo].[INVOICELOG] ([INVOICENO])
 ON [Invoice_Log_index]
go

CREATE INDEX [ix_invoicelog_pono] ON [dbo].[INVOICELOG] ([PONO])
 ON [Invoice_Log_index]
go

CREATE CLUSTERED INDEX [IX_INVOICELOG_IMAGESENT_LOGID] ON [dbo].[INVOICELOG] ([IMAGESENT] DESC,[LOGID] DESC)
 ON [Invoice_Log_index]
go


CREATE INDEX [IX_InvoiceLog_DistributorID] ON [dbo].[INVOICELOG] ([DISTRIBUTORID])
 ON [Invoice_Log_index]
go

CREATE INDEX [IX_InvoiceLog_ContractorId] ON [dbo].[INVOICELOG] ([CONTRACTORID])
 ON [Invoice_Log_index]
go

CREATE INDEX [IX_InvoiceLog_ProcessDate] ON [dbo].[INVOICELOG] ([PROCESSDATE])
 ON [Invoice_Log_index]
go


ALTER TABLE [dbo].[INVOICELOG] ADD CONSTRAINT [PK_InvoiceLog] PRIMARY KEY ([LOGID])
 ON [Invoice_Log_Data]
go

GRANT INSERT ON [dbo].[INVOICELOG] TO [mindfire] AS [dbo]
go
GRANT SELECT ON [dbo].[INVOICELOG] TO [mindfire] AS [dbo]
go
